In [9]:
# Import descrepancies
import pandas as pd 
from pathlib import Path
import matplotlib.pyplot as plt
from sklearn.linear_model import LinearRegression

In [24]:
# Load the file data into the path
file_path_01 = "/Users/linghoang/UCBBootcamp/DataClass/GroupProject/Resources/Lake_Sammamish_0611.csv"

# Load the file_path data into dataframe
WQ0611_df = pd.read_csv(file_path, skiprows=12, encoding='unicode_escape', on_bad_lines='skip')

# Show the WQ dataframe 
WQ0611_df.head(10)

,CollectDate,SampleNum,Depth (m),Ammmonia Nitrogen (mg/L),Ammmonia Nitrogen Qualifier*,AN MDL (mg/L),Conductivity (µmhos/cm),Cond Qualifier*,Cond MDL (µmhos/cm),Dissolved Oxygen (mg/L),...,Total Nitrogen (mg/L),TN Qualifier*,TN MDL (mg/L),Total Phosphorus (mg/L),TP Qualifier*,TP MDL (mg/L),Total Alkalinity (mg/L),Total Alkalinity Qualifier*,Total Alkalinity MDL (mg/L),Unnamed: 35
0,01/06/1994,L2704-18,1.0,0.02,<MDL,0.02,103.0,NaN,NaN,9.15,...,0.41,NaN,0.05,0.017,NaN,0.005,42.0,NaN,0.2,NaN
1,01/06/1994,L2704-19,5.0,NaN,NaN,NaN,104.0,NaN,NaN,8.98,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,01/06/1994,L2704-20,10.0,0.02,<MDL,0.02,102.0,NaN,NaN,9.00,...,0.44,NaN,0.05,0.019,NaN,0.005,42.0,NaN,0.2,NaN
3,01/06/1994,L2704-21,15.0,NaN,NaN,NaN,105.0,NaN,NaN,9.21,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,01/06/1994,L2704-22,20.0,NaN,NaN,NaN,104.0,NaN,NaN,9.20,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
5,01/06/1994,L2704-23,22.5,0.02,<MDL,0.02,103.0,NaN,NaN,9.19,...,0.40,NaN,0.05,0.023,NaN,0.005,42.0,NaN,0.2,NaN
6,01/06/1994,L2704-18,1.0,0.02,<MDL,0.02,103.0,NaN,NaN,9.15,...,0.41,NaN,0.05,0.017,NaN,0.005,42.0,NaN,0.2,NaN
7,02/14/1994,L2938-18,1.0,0.02,<MDL,0.02,102.5,NaN,NaN,10.81,...,0.47,NaN,0.05,0.030,NaN,0.005,NaN,NaN,NaN,NaN
8,02/14/1994,L2938-19,5.0,NaN,NaN,NaN,103.9,NaN,NaN,10.71,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
9,02/14/1994,L2938-20,10.0,0.02,<MDL,0.02,105.0,NaN,NaN,10.71,...,0.53,NaN,0.05,0.049,NaN,0.005,NaN,NaN,NaN,NaN

In [32]:
# Load the file data into the path
file_path_02 = "/Users/linghoang/UCBBootcamp/DataClass/GroupProject/Resources/Lake_Sammamish_0614.csv"

# Load the file_path data into dataframe
WQ0614_df = pd.read_csv(file_path, skiprows=12, encoding='unicode_escape', on_bad_lines='skip')

# Show the WQ dataframe 
WQ0614_df.head(20)

,CollectDate,SampleNum,Depth (m),Ammmonia Nitrogen (mg/L),Ammmonia Nitrogen Qualifier*,AN MDL (mg/L),Conductivity (µmhos/cm),Cond Qualifier*,Cond MDL (µmhos/cm),Dissolved Oxygen (mg/L),...,Total Nitrogen (mg/L),TN Qualifier*,TN MDL (mg/L),Total Phosphorus (mg/L),TP Qualifier*,TP MDL (mg/L),Total Alkalinity (mg/L),Total Alkalinity Qualifier*,Total Alkalinity MDL (mg/L),Unnamed: 35
0,01/06/1994,L2704-18,1.0,0.02,<MDL,0.02,103.0,NaN,NaN,9.15,...,0.41,NaN,0.05,0.017,NaN,0.005,42.0,NaN,0.2,NaN
1,01/06/1994,L2704-19,5.0,NaN,NaN,NaN,104.0,NaN,NaN,8.98,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,01/06/1994,L2704-20,10.0,0.02,<MDL,0.02,102.0,NaN,NaN,9.00,...,0.44,NaN,0.05,0.019,NaN,0.005,42.0,NaN,0.2,NaN
3,01/06/1994,L2704-21,15.0,NaN,NaN,NaN,105.0,NaN,NaN,9.21,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,01/06/1994,L2704-22,20.0,NaN,NaN,NaN,104.0,NaN,NaN,9.20,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
5,01/06/1994,L2704-23,22.5,0.02,<MDL,0.02,103.0,NaN,NaN,9.19,...,0.40,NaN,0.05,0.023,NaN,0.005,42.0,NaN,0.2,NaN
6,01/06/1994,L2704-18,1.0,0.02,<MDL,0.02,103.0,NaN,NaN,9.15,...,0.41,NaN,0.05,0.017,NaN,0.005,42.0,NaN,0.2,NaN
7,02/14/1994,L2938-18,1.0,0.02,<MDL,0.02,102.5,NaN,NaN,10.81,...,0.47,NaN,0.05,0.030,NaN,0.005,NaN,NaN,NaN,NaN
8,02/14/1994,L2938-19,5.0,NaN,NaN,NaN,103.9,NaN,NaN,10.71,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
9,02/14/1994,L2938-20,10.0,0.02,<MDL,0.02,105.0,NaN,NaN,10.71,...,0.53,NaN,0.05,0.049,NaN,0.005,NaN,NaN,NaN,NaN
10,02/14/1994,L2938-21,15.0,NaN,NaN,NaN,105.2,NaN,NaN,10.65,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
11,02/14/1994,L2938-22,20.0,NaN,NaN,NaN,105.2,NaN,NaN,10.62,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
12,02/14/1994,L2938-23,22.0,0.02,<MDL,0.02,105.5,NaN,NaN,10.62,...,0.50,NaN,0.05,0.029,NaN,0.005,NaN,NaN,NaN,NaN
13,02/14/1994,L2938-18,1.0,0.02,<MDL,0.02,102.5,NaN,NaN,10.81,...,0.47,NaN,0.05,0.030,NaN,0.005,NaN,NaN,NaN,NaN
14,03/08/1994,L3136-18,1.0,0.02,<MDL,0.02,103.4,NaN,NaN,11.50,...,0.53,NaN,0.05,0.013,NaN,0.005,NaN,NaN,NaN,NaN
15,03/08/1994,L3136-19,5.0,NaN,NaN,NaN,104.0,NaN,NaN,11.06,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
16,03/08/1994,L3136-20,10.0,0.02,<MDL,0.02,105.1,NaN,NaN,10.97,...,0.55,NaN,0.05,0.013,NaN,0.005,NaN,NaN,NaN,NaN
17,03/08/1994,L3136-21,15.0,NaN,NaN,NaN,105.3,NaN,NaN,10.80,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
18,03/08/1994,L3136-22,20.0,NaN,NaN,NaN,105.9,NaN,NaN,10.14,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
19,03/08/1994,L3136-23,22.0,0.02,<MDL,0.02,105.3,NaN,NaN,9.69,...,0.54,NaN,0.05,0.015,NaN,0.005,NaN,NaN,NaN,NaN

In [26]:
# Load the file data into the path
file_path_03 = "/Users/linghoang/UCBBootcamp/DataClass/GroupProject/Resources/Lake_Sammamish_0617.csv"

# Load the file_path data into dataframe
WQ0617_df = pd.read_csv(file_path, skiprows=12, encoding='unicode_escape', on_bad_lines='skip')

# Show the WQ dataframe 
WQ0617_df.head(10)

,CollectDate,SampleNum,Depth (m),Ammmonia Nitrogen (mg/L),Ammmonia Nitrogen Qualifier*,AN MDL (mg/L),Conductivity (µmhos/cm),Cond Qualifier*,Cond MDL (µmhos/cm),Dissolved Oxygen (mg/L),...,Total Nitrogen (mg/L),TN Qualifier*,TN MDL (mg/L),Total Phosphorus (mg/L),TP Qualifier*,TP MDL (mg/L),Total Alkalinity (mg/L),Total Alkalinity Qualifier*,Total Alkalinity MDL (mg/L),Unnamed: 35
0,01/06/1994,L2704-18,1.0,0.02,<MDL,0.02,103.0,NaN,NaN,9.15,...,0.41,NaN,0.05,0.017,NaN,0.005,42.0,NaN,0.2,NaN
1,01/06/1994,L2704-19,5.0,NaN,NaN,NaN,104.0,NaN,NaN,8.98,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,01/06/1994,L2704-20,10.0,0.02,<MDL,0.02,102.0,NaN,NaN,9.00,...,0.44,NaN,0.05,0.019,NaN,0.005,42.0,NaN,0.2,NaN
3,01/06/1994,L2704-21,15.0,NaN,NaN,NaN,105.0,NaN,NaN,9.21,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,01/06/1994,L2704-22,20.0,NaN,NaN,NaN,104.0,NaN,NaN,9.20,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
5,01/06/1994,L2704-23,22.5,0.02,<MDL,0.02,103.0,NaN,NaN,9.19,...,0.40,NaN,0.05,0.023,NaN,0.005,42.0,NaN,0.2,NaN
6,01/06/1994,L2704-18,1.0,0.02,<MDL,0.02,103.0,NaN,NaN,9.15,...,0.41,NaN,0.05,0.017,NaN,0.005,42.0,NaN,0.2,NaN
7,02/14/1994,L2938-18,1.0,0.02,<MDL,0.02,102.5,NaN,NaN,10.81,...,0.47,NaN,0.05,0.030,NaN,0.005,NaN,NaN,NaN,NaN
8,02/14/1994,L2938-19,5.0,NaN,NaN,NaN,103.9,NaN,NaN,10.71,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
9,02/14/1994,L2938-20,10.0,0.02,<MDL,0.02,105.0,NaN,NaN,10.71,...,0.53,NaN,0.05,0.049,NaN,0.005,NaN,NaN,NaN,NaN

In [27]:
# Load the file data into the path
file_path_04 = "/Users/linghoang/UCBBootcamp/DataClass/GroupProject/Resources/Lake_Sammamish_0622.csv"

# Load the file_path data into dataframe
WQ0622_df = pd.read_csv(file_path, skiprows=12, encoding='unicode_escape', on_bad_lines='skip')

# Show the WQ dataframe 
WQ0622_df.head(10)

,CollectDate,SampleNum,Depth (m),Ammmonia Nitrogen (mg/L),Ammmonia Nitrogen Qualifier*,AN MDL (mg/L),Conductivity (µmhos/cm),Cond Qualifier*,Cond MDL (µmhos/cm),Dissolved Oxygen (mg/L),...,Total Nitrogen (mg/L),TN Qualifier*,TN MDL (mg/L),Total Phosphorus (mg/L),TP Qualifier*,TP MDL (mg/L),Total Alkalinity (mg/L),Total Alkalinity Qualifier*,Total Alkalinity MDL (mg/L),Unnamed: 35
0,01/06/1994,L2704-18,1.0,0.02,<MDL,0.02,103.0,NaN,NaN,9.15,...,0.41,NaN,0.05,0.017,NaN,0.005,42.0,NaN,0.2,NaN
1,01/06/1994,L2704-19,5.0,NaN,NaN,NaN,104.0,NaN,NaN,8.98,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,01/06/1994,L2704-20,10.0,0.02,<MDL,0.02,102.0,NaN,NaN,9.00,...,0.44,NaN,0.05,0.019,NaN,0.005,42.0,NaN,0.2,NaN
3,01/06/1994,L2704-21,15.0,NaN,NaN,NaN,105.0,NaN,NaN,9.21,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,01/06/1994,L2704-22,20.0,NaN,NaN,NaN,104.0,NaN,NaN,9.20,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
5,01/06/1994,L2704-23,22.5,0.02,<MDL,0.02,103.0,NaN,NaN,9.19,...,0.40,NaN,0.05,0.023,NaN,0.005,42.0,NaN,0.2,NaN
6,01/06/1994,L2704-18,1.0,0.02,<MDL,0.02,103.0,NaN,NaN,9.15,...,0.41,NaN,0.05,0.017,NaN,0.005,42.0,NaN,0.2,NaN
7,02/14/1994,L2938-18,1.0,0.02,<MDL,0.02,102.5,NaN,NaN,10.81,...,0.47,NaN,0.05,0.030,NaN,0.005,NaN,NaN,NaN,NaN
8,02/14/1994,L2938-19,5.0,NaN,NaN,NaN,103.9,NaN,NaN,10.71,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
9,02/14/1994,L2938-20,10.0,0.02,<MDL,0.02,105.0,NaN,NaN,10.71,...,0.53,NaN,0.05,0.049,NaN,0.005,NaN,NaN,NaN,NaN

In [28]:
# Load the file data into the path
file_path_04 = "/Users/linghoang/UCBBootcamp/DataClass/GroupProject/Resources/Lake_Sammamish_0625.csv"

# Load the file_path data into dataframe
WQ0625_df = pd.read_csv(file_path, skiprows=12, encoding='unicode_escape', on_bad_lines='skip')

# Show the WQ dataframe 
WQ0625_df.head(10)

,CollectDate,SampleNum,Depth (m),Ammmonia Nitrogen (mg/L),Ammmonia Nitrogen Qualifier*,AN MDL (mg/L),Conductivity (µmhos/cm),Cond Qualifier*,Cond MDL (µmhos/cm),Dissolved Oxygen (mg/L),...,Total Nitrogen (mg/L),TN Qualifier*,TN MDL (mg/L),Total Phosphorus (mg/L),TP Qualifier*,TP MDL (mg/L),Total Alkalinity (mg/L),Total Alkalinity Qualifier*,Total Alkalinity MDL (mg/L),Unnamed: 35
0,01/06/1994,L2704-18,1.0,0.02,<MDL,0.02,103.0,NaN,NaN,9.15,...,0.41,NaN,0.05,0.017,NaN,0.005,42.0,NaN,0.2,NaN
1,01/06/1994,L2704-19,5.0,NaN,NaN,NaN,104.0,NaN,NaN,8.98,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,01/06/1994,L2704-20,10.0,0.02,<MDL,0.02,102.0,NaN,NaN,9.00,...,0.44,NaN,0.05,0.019,NaN,0.005,42.0,NaN,0.2,NaN
3,01/06/1994,L2704-21,15.0,NaN,NaN,NaN,105.0,NaN,NaN,9.21,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,01/06/1994,L2704-22,20.0,NaN,NaN,NaN,104.0,NaN,NaN,9.20,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
5,01/06/1994,L2704-23,22.5,0.02,<MDL,0.02,103.0,NaN,NaN,9.19,...,0.40,NaN,0.05,0.023,NaN,0.005,42.0,NaN,0.2,NaN
6,01/06/1994,L2704-18,1.0,0.02,<MDL,0.02,103.0,NaN,NaN,9.15,...,0.41,NaN,0.05,0.017,NaN,0.005,42.0,NaN,0.2,NaN
7,02/14/1994,L2938-18,1.0,0.02,<MDL,0.02,102.5,NaN,NaN,10.81,...,0.47,NaN,0.05,0.030,NaN,0.005,NaN,NaN,NaN,NaN
8,02/14/1994,L2938-19,5.0,NaN,NaN,NaN,103.9,NaN,NaN,10.71,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
9,02/14/1994,L2938-20,10.0,0.02,<MDL,0.02,105.0,NaN,NaN,10.71,...,0.53,NaN,0.05,0.049,NaN,0.005,NaN,NaN,NaN,NaN

In [29]:
# Load the file data into the path
file_path_05 = "/Users/linghoang/UCBBootcamp/DataClass/GroupProject/Resources/Lake_Sammamish_M621.csv"

# Load the file_path data into dataframe
WQM621_df = pd.read_csv(file_path, skiprows=12, encoding='unicode_escape', on_bad_lines='skip')

# Show the WQ dataframe 
WQM621_df.head(10)

,CollectDate,SampleNum,Depth (m),Ammmonia Nitrogen (mg/L),Ammmonia Nitrogen Qualifier*,AN MDL (mg/L),Conductivity (µmhos/cm),Cond Qualifier*,Cond MDL (µmhos/cm),Dissolved Oxygen (mg/L),...,Total Nitrogen (mg/L),TN Qualifier*,TN MDL (mg/L),Total Phosphorus (mg/L),TP Qualifier*,TP MDL (mg/L),Total Alkalinity (mg/L),Total Alkalinity Qualifier*,Total Alkalinity MDL (mg/L),Unnamed: 35
0,01/06/1994,L2704-18,1.0,0.02,<MDL,0.02,103.0,NaN,NaN,9.15,...,0.41,NaN,0.05,0.017,NaN,0.005,42.0,NaN,0.2,NaN
1,01/06/1994,L2704-19,5.0,NaN,NaN,NaN,104.0,NaN,NaN,8.98,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,01/06/1994,L2704-20,10.0,0.02,<MDL,0.02,102.0,NaN,NaN,9.00,...,0.44,NaN,0.05,0.019,NaN,0.005,42.0,NaN,0.2,NaN
3,01/06/1994,L2704-21,15.0,NaN,NaN,NaN,105.0,NaN,NaN,9.21,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,01/06/1994,L2704-22,20.0,NaN,NaN,NaN,104.0,NaN,NaN,9.20,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
5,01/06/1994,L2704-23,22.5,0.02,<MDL,0.02,103.0,NaN,NaN,9.19,...,0.40,NaN,0.05,0.023,NaN,0.005,42.0,NaN,0.2,NaN
6,01/06/1994,L2704-18,1.0,0.02,<MDL,0.02,103.0,NaN,NaN,9.15,...,0.41,NaN,0.05,0.017,NaN,0.005,42.0,NaN,0.2,NaN
7,02/14/1994,L2938-18,1.0,0.02,<MDL,0.02,102.5,NaN,NaN,10.81,...,0.47,NaN,0.05,0.030,NaN,0.005,NaN,NaN,NaN,NaN
8,02/14/1994,L2938-19,5.0,NaN,NaN,NaN,103.9,NaN,NaN,10.71,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
9,02/14/1994,L2938-20,10.0,0.02,<MDL,0.02,105.0,NaN,NaN,10.71,...,0.53,NaN,0.05,0.049,NaN,0.005,NaN,NaN,NaN,NaN

In [30]:
# Load the file data into the path
file_path_04 = "/Users/linghoang/UCBBootcamp/DataClass/GroupProject/Resources/Lake_Sammamish_0622.csv"

# Load the file_path data into dataframe
WQ0622_df = pd.read_csv(file_path, skiprows=12, encoding='unicode_escape', on_bad_lines='skip')

# Show the WQ dataframe 
WQ0622_df.head(10)

,CollectDate,SampleNum,Depth (m),Ammmonia Nitrogen (mg/L),Ammmonia Nitrogen Qualifier*,AN MDL (mg/L),Conductivity (µmhos/cm),Cond Qualifier*,Cond MDL (µmhos/cm),Dissolved Oxygen (mg/L),...,Total Nitrogen (mg/L),TN Qualifier*,TN MDL (mg/L),Total Phosphorus (mg/L),TP Qualifier*,TP MDL (mg/L),Total Alkalinity (mg/L),Total Alkalinity Qualifier*,Total Alkalinity MDL (mg/L),Unnamed: 35
0,01/06/1994,L2704-18,1.0,0.02,<MDL,0.02,103.0,NaN,NaN,9.15,...,0.41,NaN,0.05,0.017,NaN,0.005,42.0,NaN,0.2,NaN
1,01/06/1994,L2704-19,5.0,NaN,NaN,NaN,104.0,NaN,NaN,8.98,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,01/06/1994,L2704-20,10.0,0.02,<MDL,0.02,102.0,NaN,NaN,9.00,...,0.44,NaN,0.05,0.019,NaN,0.005,42.0,NaN,0.2,NaN
3,01/06/1994,L2704-21,15.0,NaN,NaN,NaN,105.0,NaN,NaN,9.21,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,01/06/1994,L2704-22,20.0,NaN,NaN,NaN,104.0,NaN,NaN,9.20,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
5,01/06/1994,L2704-23,22.5,0.02,<MDL,0.02,103.0,NaN,NaN,9.19,...,0.40,NaN,0.05,0.023,NaN,0.005,42.0,NaN,0.2,NaN
6,01/06/1994,L2704-18,1.0,0.02,<MDL,0.02,103.0,NaN,NaN,9.15,...,0.41,NaN,0.05,0.017,NaN,0.005,42.0,NaN,0.2,NaN
7,02/14/1994,L2938-18,1.0,0.02,<MDL,0.02,102.5,NaN,NaN,10.81,...,0.47,NaN,0.05,0.030,NaN,0.005,NaN,NaN,NaN,NaN
8,02/14/1994,L2938-19,5.0,NaN,NaN,NaN,103.9,NaN,NaN,10.71,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
9,02/14/1994,L2938-20,10.0,0.02,<MDL,0.02,105.0,NaN,NaN,10.71,...,0.53,NaN,0.05,0.049,NaN,0.005,NaN,NaN,NaN,NaN