In [1]:
import pandas as pd
import numpy as np
from pathlib import Path
import matplotlib.pyplot as plt
import time

In [4]:

file_path = "Resources/Lake_Sammamish_0612_1_1_1994_to_9_30_2022.csv"

WQ0612_df = pd.read_csv(file_path, skiprows=12, encoding='unicode_escape', on_bad_lines='skip')

WQ0612_df.head(10)

/var/folders/25/v262f3893210tshrdcyr9ly80000gn/T/ipykernel_23563/1117231833.py:3: DtypeWarning: Columns (2,7,13,15,23,25,33) have mixed types. Specify dtype option on import or set low_memory=False.
  WQ0612_df = pd.read_csv(file_path, skiprows=12, encoding='unicode_escape', on_bad_lines='skip')

,CollectDate,SampleNum,Depth (m),Ammmonia Nitrogen (mg/L),Ammmonia Nitrogen Qualifier*,AN MDL (mg/L),Conductivity (µmhos/cm),Cond Qualifier*,Cond MDL (µmhos/cm),Dissolved Oxygen (mg/L),...,Total Nitrogen (mg/L),TN Qualifier*,TN MDL (mg/L),Total Phosphorus (mg/L),TP Qualifier*,TP MDL (mg/L),Total Alkalinity (mg/L),Total Alkalinity Qualifier*,Total Alkalinity MDL (mg/L),Unnamed: 35
0,01/06/1994,L2704-5,1.0,0.02,<MDL,0.02,102.0,NaN,NaN,9.17,...,0.39,NaN,0.05,0.020,NaN,0.005,42.0,NaN,0.2,NaN
1,01/06/1994,L2704-6,5.0,NaN,NaN,NaN,105.0,NaN,NaN,8.88,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,01/06/1994,L2704-7,10.0,0.02,<MDL,0.02,104.0,NaN,NaN,9.25,...,0.47,NaN,0.05,0.026,NaN,0.005,42.0,NaN,0.2,NaN
3,01/06/1994,L2704-8,15.0,NaN,NaN,NaN,104.0,NaN,NaN,9.22,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,01/06/1994,L2704-9,20.0,NaN,NaN,NaN,103.0,NaN,NaN,9.21,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
5,01/06/1994,L2704-10,25.0,0.02,<MDL,0.02,105.0,NaN,NaN,9.08,...,0.46,NaN,0.05,0.023,NaN,0.005,38.0,NaN,0.2,NaN
6,01/06/1994,L2704-5,1.0,0.02,<MDL,0.02,102.0,NaN,NaN,9.17,...,0.39,NaN,0.05,0.020,NaN,0.005,42.0,NaN,0.2,NaN
7,02/14/1994,L2938-5,1.0,0.02,<MDL,0.02,102.4,NaN,NaN,10.77,...,0.50,NaN,0.05,0.027,NaN,0.005,NaN,NaN,NaN,NaN
8,02/14/1994,L2938-6,5.0,NaN,NaN,NaN,103.9,NaN,NaN,10.61,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
9,02/14/1994,L2938-7,10.0,0.02,<MDL,0.02,105.1,NaN,NaN,10.58,...,0.50,NaN,0.05,0.041,NaN,0.005,NaN,NaN,NaN,NaN

In [5]:
WQ0612_df.count()

CollectDate                        19929
SampleNum                          19929
Depth (m)                          19908
Ammmonia Nitrogen (mg/L)            2720
Ammmonia Nitrogen Qualifier*        2362
AN MDL (mg/L)                       2872
Conductivity (µmhos/cm)            17791
Cond Qualifier*                      993
Cond MDL (µmhos/cm)                15573
Dissolved Oxygen (mg/L)            17495
DO Qualifier*                       2582
DO MDL (mg/L)                      15559
Ecoli                                172
Ecoli Qualifier*                       4
Fecal Coliform (CFU/100ml)           317
Fecal Coliform Qualifier*              2
Nitrate Nitrite (mg/L)              2784
Nitrate Nitrite Qualifier*           560
Nitrate Nitrite MDL (mg/L)          2872
Orthophosphate Phosphate (mg/L)     2711
OP Qualifier*                       1863
OP MDL (mg/L)                       2869
pH                                 17795
pH Qualifier*                        982
Temperature (°C)                   17810
Temperature Qualifier*               982
Total Nitrogen (mg/L)               2868
TN Qualifier*                        136
TN MDL (mg/L)                       2868
Total Phosphorus (mg/L)             2976
TP Qualifier*                       1142
TP MDL (mg/L)                       2993
Total Alkalinity (mg/L)             2003
Total Alkalinity Qualifier*           22
Total Alkalinity MDL (mg/L)         2007
Unnamed: 35                            0
dtype: int64

In [6]:
WQ0612_df.columns

Index(['CollectDate', 'SampleNum', 'Depth (m)', 'Ammmonia Nitrogen (mg/L)',
       'Ammmonia Nitrogen Qualifier*', 'AN MDL (mg/L)',
       'Conductivity (µmhos/cm)', 'Cond Qualifier*', 'Cond MDL (µmhos/cm)',
       'Dissolved Oxygen (mg/L)', 'DO Qualifier*', 'DO MDL (mg/L)', 'Ecoli',
       'Ecoli Qualifier*', 'Fecal Coliform (CFU/100ml)',
       'Fecal Coliform Qualifier*', 'Nitrate Nitrite (mg/L)',
       'Nitrate Nitrite Qualifier*', 'Nitrate Nitrite MDL (mg/L)',
       'Orthophosphate Phosphate (mg/L)', 'OP Qualifier*', 'OP MDL (mg/L)',
       'pH', 'pH Qualifier*', 'Temperature (°C)', 'Temperature Qualifier*',
       'Total Nitrogen (mg/L)', 'TN Qualifier*', 'TN MDL (mg/L)',
       'Total Phosphorus (mg/L)', 'TP Qualifier*', 'TP MDL (mg/L)',
       'Total Alkalinity (mg/L)', 'Total Alkalinity Qualifier*',
       'Total Alkalinity MDL (mg/L)', 'Unnamed: 35'],
      dtype='object')