## Logistic Regression

In [1]:
# Import descrepancies
import pandas as pd 
from pathlib import Path
import matplotlib.pyplot as plt
from sklearn.linear_model import LinearRegression

In [2]:
# Load the file data into the path
file_path = "/Users/linghoang/UCBBootcamp/DataClass/GroupProject/Final_Project_UCB_Bootcamp/Ritu_Gothwal/Resources_Ritu/Big_lake_Sammamish.csv"

# Load the file_path data into dataframe
Big_Lake_df = pd.read_csv(file_path)

# Show the WQ dataframe 
Big_Lake_df.head(10)

,Unnamed: 0,CollectDate,Ammmonia Nitrogen (mg/L),Conductivity (µmhos/cm),Dissolved Oxygen (mg/L),Fecal Coliform (CFU/100ml),Nitrate Nitrite (mg/L),Orthophosphate Phosphate (mg/L),pH,Temperature (°C),Total Nitrogen (mg/L),Total Phosphorus (mg/L),WQI
0,0,1994-01-06,0.02,103.0,9.15,1.0,0.270000,0.011,7.4,7.4,0.410000,0.017000,94.891147
1,1,1994-01-06,0.02,104.0,8.98,1.0,0.280000,0.012,7.4,7.3,0.416667,0.019667,98.699450
2,2,1994-01-06,0.02,102.0,9.00,1.0,0.290000,0.012,7.4,7.3,0.440000,0.019000,101.553997
3,3,1994-01-06,0.02,105.0,9.21,1.0,0.280000,0.012,7.4,7.3,0.416667,0.019667,98.722325
4,4,1994-01-06,0.02,104.0,9.20,1.0,0.280000,0.012,7.4,7.3,0.416667,0.019667,98.721299
5,5,1994-01-06,0.02,103.0,9.19,1.0,0.280000,0.013,7.4,7.3,0.400000,0.023000,99.698928
6,6,1994-02-14,0.02,102.5,10.81,7.0,0.310000,0.009,7.4,6.5,0.470000,0.030000,111.025363
7,7,1994-02-14,0.02,103.9,10.71,7.0,0.296667,0.009,7.4,6.5,0.500000,0.036000,108.874964
8,8,1994-02-14,0.02,105.0,10.71,7.0,0.260000,0.009,7.4,6.5,0.530000,0.049000,101.827577
9,9,1994-02-14,0.02,105.2,10.65,7.0,0.296667,0.009,7.4,6.5,0.500000,0.036000,108.869049

In [3]:
Big_Lake_df.columns

Index(['Unnamed: 0', 'CollectDate', 'Ammmonia Nitrogen (mg/L)',
       'Conductivity (µmhos/cm)', 'Dissolved Oxygen (mg/L)',
       'Fecal Coliform (CFU/100ml)', 'Nitrate Nitrite (mg/L)',
       'Orthophosphate Phosphate (mg/L)', 'pH', 'Temperature (°C)',
       'Total Nitrogen (mg/L)', 'Total Phosphorus (mg/L)', 'WQI'],
      dtype='object')

In [5]:
Big_Lake_df = Big_Lake_df.drop(columns=["Unnamed: 0"])

In [6]:
Big_Lake_df

,CollectDate,Ammmonia Nitrogen (mg/L),Conductivity (µmhos/cm),Dissolved Oxygen (mg/L),Fecal Coliform (CFU/100ml),Nitrate Nitrite (mg/L),Orthophosphate Phosphate (mg/L),pH,Temperature (°C),Total Nitrogen (mg/L),Total Phosphorus (mg/L),WQI
0,1994-01-06,0.02,103.00,9.15,1.0,0.270,0.011000,7.400,7.4,0.410000,0.017000,94.891147
1,1994-01-06,0.02,104.00,8.98,1.0,0.280,0.012000,7.400,7.3,0.416667,0.019667,98.699450
2,1994-01-06,0.02,102.00,9.00,1.0,0.290,0.012000,7.400,7.3,0.440000,0.019000,101.553997
3,1994-01-06,0.02,105.00,9.21,1.0,0.280,0.012000,7.400,7.3,0.416667,0.019667,98.722325
4,1994-01-06,0.02,104.00,9.20,1.0,0.280,0.012000,7.400,7.3,0.416667,0.019667,98.721299
...,...,...,...,...,...,...,...,...,...,...,...,...
9508,2008-12-09,0.01,103.00,8.00,37.0,0.209,0.008467,7.300,10.4,0.359000,0.017300,73.585895
9509,2008-12-09,0.01,102.00,7.90,37.0,0.209,0.008467,7.300,10.4,0.359000,0.017300,73.575930
9510,2008-12-09,0.01,102.00,7.80,37.0,0.209,0.008467,7.300,10.4,0.359000,0.017300,73.565999
9511,2008-12-09,0.01,102.25,7.90,37.0,0.210,0.008500,7.275,10.4,0.359000,0.017700,73.995892
9512,2008-12-09,0.01,102.00,7.90,37.0,0.209,0.008467,7.200,10.4,0.359000,0.017300,73.571772

In [10]:
import numpy as np

In [11]:
WQI_Conditions = [
    (Big_Lake_df['WQI'] <= 25),
    (Big_Lake_df['WQI'] >= 26) & (Big_Lake_df['WQI'] <= 50),
    (Big_Lake_df['WQI'] >= 51) & (Big_Lake_df['WQI'] <= 75),
    (Big_Lake_df['WQI'] >= 76) & (Big_Lake_df['WQI'] <= 90),
    (Big_Lake_df['WQI'] >= 91) & (Big_Lake_df['WQI'] <= 100), 
    (Big_Lake_df['WQI'] > 101)
]

WQI_Categories = ['0', '1', '2', '3', '4', '5']

Big_Lake_df['WQ'] = np.select(WQI_Conditions, WQI_Categories) 

Big_Lake_df.head(50)

,CollectDate,Ammmonia Nitrogen (mg/L),Conductivity (µmhos/cm),Dissolved Oxygen (mg/L),Fecal Coliform (CFU/100ml),Nitrate Nitrite (mg/L),Orthophosphate Phosphate (mg/L),pH,Temperature (°C),Total Nitrogen (mg/L),Total Phosphorus (mg/L),WQI,WQ
0,1994-01-06,0.02,103.0,9.15,1.0,0.270000,0.0110,7.4,7.4,0.410000,0.017000,94.891147,4
1,1994-01-06,0.02,104.0,8.98,1.0,0.280000,0.0120,7.4,7.3,0.416667,0.019667,98.699450,4
2,1994-01-06,0.02,102.0,9.00,1.0,0.290000,0.0120,7.4,7.3,0.440000,0.019000,101.553997,5
3,1994-01-06,0.02,105.0,9.21,1.0,0.280000,0.0120,7.4,7.3,0.416667,0.019667,98.722325,4
4,1994-01-06,0.02,104.0,9.20,1.0,0.280000,0.0120,7.4,7.3,0.416667,0.019667,98.721299,4
5,1994-01-06,0.02,103.0,9.19,1.0,0.280000,0.0130,7.4,7.3,0.400000,0.023000,99.698928,4
6,1994-02-14,0.02,102.5,10.81,7.0,0.310000,0.0090,7.4,6.5,0.470000,0.030000,111.025363,5
7,1994-02-14,0.02,103.9,10.71,7.0,0.296667,0.0090,7.4,6.5,0.500000,0.036000,108.874964,5
8,1994-02-14,0.02,105.0,10.71,7.0,0.260000,0.0090,7.4,6.5,0.530000,0.049000,101.827577,5
9,1994-02-14,0.02,105.2,10.65,7.0,0.296667,0.0090,7.4,6.5,0.500000,0.036000,108.869049,5
10,1994-02-14,0.02,105.2,10.62,7.0,0.296667,0.0090,7.4,6.5,0.500000,0.036000,108.866069,5
11,1994-02-14,0.02,105.5,10.62,7.0,0.320000,0.0090,7.4,6.5,0.500000,0.029000,113.772989,5
12,1994-03-08,0.02,103.4,11.50,0.0,0.280000,0.0030,7.8,7.5,0.530000,0.013000,97.103901,4
13,1994-03-08,0.02,104.0,11.06,0.0,0.326667,0.0050,7.6,7.1,0.540000,0.013667,111.292302,5
14,1994-03-08,0.02,105.1,10.97,0.0,0.380000,0.0030,7.6,7.1,0.550000,0.013000,127.102509,5
15,1994-03-08,0.02,105.3,10.80,0.0,0.326667,0.0050,7.5,6.9,0.540000,0.013667,111.250104,5
16,1994-03-08,0.02,105.9,10.14,0.0,0.326667,0.0050,7.4,6.7,0.540000,0.013667,111.168157,5
17,1994-03-08,0.02,105.3,9.69,0.0,0.320000,0.0090,7.3,6.5,0.540000,0.015000,109.552837,5
18,1994-03-22,0.02,104.0,12.63,0.0,0.290000,0.0020,8.7,8.0,0.500000,0.016000,101.115118,5
19,1994-03-22,0.02,105.3,12.24,0.0,0.300000,0.0020,8.3,7.6,0.515000,0.015000,103.770373,5
20,1994-03-22,0.02,105.9,11.91,0.0,0.310000,0.0020,8.1,7.6,0.530000,0.014000,106.464405,5
21,1994-03-22,0.02,106.2,11.76,0.0,0.300000,0.0020,8.1,7.5,0.515000,0.015000,103.708286,5
22,1994-03-22,0.02,106.3,11.71,0.0,0.300000,0.0020,8.1,7.5,0.515000,0.015000,103.703323,5
23,1994-03-22,0.02,106.5,11.70,0.0,0.300000,0.0020,8.1,7.5,0.515000,0.015000,103.702337,5
24,1994-04-05,0.02,103.7,15.04,4.0,0.223000,0.0047,9.4,10.3,0.439000,0.009000,79.199113,3
25,1994-04-05,0.02,104.2,15.01,4.0,0.286333,0.0047,9.3,10.0,0.472667,0.010333,98.671193,4
26,1994-04-05,0.02,103.3,13.28,4.0,0.276000,0.0047,8.7,7.9,0.454000,0.009000,94.801770,4
27,1994-04-05,0.02,103.3,11.83,4.0,0.286333,0.0047,7.9,7.4,0.472667,0.010333,98.137724,4
28,1994-04-05,0.02,103.7,11.13,4.0,0.286333,0.0047,7.7,7.2,0.472667,0.010333,98.047640,4
29,1994-04-05,0.02,103.9,9.59,4.0,0.360000,0.0047,7.4,7.1,0.525000,0.013000,120.917571,5
30,1994-04-19,0.02,104.5,12.89,0.0,0.241000,0.0020,9.2,12.6,0.427000,0.011000,85.068635,3
31,1994-04-19,0.02,105.0,12.89,0.0,0.278000,0.0020,9.2,12.5,0.474333,0.014000,97.178192,4
32,1994-04-19,0.02,103.9,13.65,0.0,0.252000,0.0020,9.2,9.5,0.469000,0.018000,90.449267,0
33,1994-04-19,0.02,103.6,12.52,0.0,0.278000,0.0020,8.7,8.7,0.474333,0.014000,96.887627,4
34,1994-04-19,0.02,104.1,11.35,0.0,0.278000,0.0020,8.0,8.0,0.474333,0.014000,96.699423,4
35,1994-04-19,0.02,104.1,9.31,0.0,0.341000,0.0020,7.5,7.5,0.527000,0.013000,115.181483,5
36,1994-05-03,0.02,108.3,10.84,0.0,0.251000,0.0020,8.8,13.8,0.416000,0.008000,87.002122,3
37,1994-05-03,0.02,108.5,10.53,0.0,0.284333,0.0020,8.8,13.4,0.460000,0.009333,97.453278,4
38,1994-05-03,0.02,107.0,12.69,0.0,0.276000,0.0020,8.7,9.4,0.454000,0.008000,94.501737,4
39,1994-05-03,0.02,106.6,11.29,0.0,0.284333,0.0020,7.9,8.2,0.460000,0.009333,97.172454,4
40,1994-05-03,0.02,106.3,8.51,0.0,0.284333,0.0020,7.2,7.7,0.460000,0.009333,96.836590,4
41,1994-05-03,0.02,106.4,8.31,0.0,0.326000,0.0020,7.1,7.6,0.510000,0.012000,110.229510,5
42,1994-05-24,0.02,114.1,10.21,0.0,0.264000,0.0020,8.4,17.7,0.428000,0.015000,93.195724,4
43,1994-05-24,0.02,114.2,10.16,0.0,0.278667,0.0020,8.5,16.8,0.438000,0.016000,97.867230,4
44,1994-05-24,0.02,113.7,10.56,0.0,0.278667,0.0020,8.5,15.8,0.438000,0.016000,97.845628,4
45,1994-05-24,0.02,113.4,10.77,0.0,0.278667,0.0020,8.6,15.2,0.438000,0.016000,97.833845,4
46,1994-05-24,0.02,113.1,11.09,0.0,0.278667,0.0020,8.6,14.2,0.438000,0.016000,97.804305,4
47,1994-05-24,0.02,112.4,11.55,0.0,0.278667,0.0020,8.6,13.0,0.438000,0.016000,97.776393,4
48,1994-05-24,0.02,112.1,11.63,0.0,0.278667,0.0020,8.6,12.4,0.438000,0.016000,97.747541,4
49,1994-05-24,0.02,111.5,11.89,0.0,0.278667,0.0020,8.6,11.7,0.438000,0.016000,97.730425,4

In [12]:
# Export csv file 

path = "/Users/linghoang/UCBBootcamp/DataClass/GroupProject/Resources/Output/Big_Lake.csv"
Big_Lake_df.to_csv(path, index=False)

## Set Up Logistic Regression Model

In [13]:
import matplotlib.pyplot as plt
import pandas as pd
from sklearn.linear_model import LogisticRegression

In [20]:
# Seperate the Features (X) from the Target (y)
y = Big_Lake_df['WQ']
X = Big_Lake_df.drop(['WQ', 'CollectDate'], axis='columns')

In [21]:
# Split our data into training and testing 
from sklearn.model_selection import train_test_split

X_train, X_test, y_train, y_test = train_test_split(X, y,random_state=42)
                                                    
                                                    
X_train.shape

(7134, 11)

In [22]:
y_train

5998    4
2586    3
435     3
6496    0
308     5
       ..
5734    3
5191    4
5390    0
860     2
7270    0
Name: WQ, Length: 7134, dtype: object

In [23]:
y_test

7094    5
4692    3
6676    2
7764    2
3254    5
       ..
7614    5
524     2
5909    2
6192    1
6567    2
Name: WQ, Length: 2379, dtype: object

In [24]:
# Create a Logistic Regression Model 

classifier = LogisticRegression(solver='lbfgs', random_state=0)
classifier

LogisticRegression(random_state=0)

In [25]:
classifier.fit(X_train, y_train)

/Users/linghoang/opt/anaconda3/envs/mlenv/lib/python3.7/site-packages/sklearn/linear_model/_logistic.py:818: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  extra_warning_msg=_LOGISTIC_SOLVER_CONVERGENCE_MSG,

LogisticRegression(random_state=0)

In [26]:
from sklearn import preprocessing
from sklearn import utils

In [27]:
# convert y values to categorical values
lab = preprocessing.LabelEncoder()
y_transformed = lab.fit_transform(y)

In [29]:
#view transformed values
print(y_transformed)

[4 4 5 ... 2 2 2]

In [30]:
# Fit (train) or model using the training data 
classifier.fit(X, y_transformed)

/Users/linghoang/opt/anaconda3/envs/mlenv/lib/python3.7/site-packages/sklearn/linear_model/_logistic.py:818: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  extra_warning_msg=_LOGISTIC_SOLVER_CONVERGENCE_MSG,

LogisticRegression(random_state=0)

In [31]:
# Prediction outcomes for test data set 
predictions = classifier.predict(X_test)

results = pd.DataFrame({"Prediction": predictions, "Actual": y_test}).reset_index(drop=True)
results.head(20)

    Prediction Actual
0            5      5
1            2      3
2            2      2
3            2      2
4            5      5
5            0      1
6            2      2
7            5      5
8            2      3
9            2      2
10           5      0
11           4      0
12           0      1
13           4      4
14           5      5
15           5      5
16           0      1
17           2      2
18           2      2
19           2      2

In [32]:
from sklearn.metrics import accuracy_score
print(accuracy_score(y_test, predictions))

0.0